const express = require('express');
const router = express.Router();
const { authenticate, isClient } = require('../middleware/auth.middleware');
const { Order, WalletTransaction, Wallet } = require('../models');

// Initialize payment
router.post('/initiate', authenticate, isClient, async (req, res) => {
  try {
    const { order_id, payment_method } = req.body;

    const order = await Order.findOne({
      where: { id: order_id, user_id: req.user.id }
    });

    if (!order) {
      return res.status(404).json({ success: false, error: 'Order not found' });
    }

    if (order.payment_status === 1) {
      return res.status(400).json({ success: false, error: 'Order already paid' });
    }

    // Handle Cash on Delivery
    if (payment_method === 'cod') {
      await order.update({
        payment_status: 0,
        payment_gateway: 'cod',
        transaction_id: `COD${Date.now()}`
      });

      return res.json({ success: true, message: 'Order placed with Cash on Delivery', data: { order_id: order.id } });
    }

    // Handle wallet payment
    if (payment_method === 'wallet') {
      const wallet = await Wallet.findOne({ where: { user_id: req.user.id } });

      if (!wallet || parseFloat(wallet.available_balance) < parseFloat(order.total)) {
        return res.status(400).json({ success: false, error: 'Insufficient wallet balance' });
      }

      // Deduct from wallet
      const newBalance = parseFloat(wallet.available_balance) - parseFloat(order.total);
      await wallet.update({ available_balance: newBalance });

      // Create transaction
      await WalletTransaction.create({
        wallet_id: wallet.id,
        user_id: req.user.id,
        type: 'debit',
        amount: order.total,
        balance_after: newBalance,
        description: `Payment for order #${order.invoice_number}`,
        reference_type: 'order',
        reference_id: order.id
      });

      // Update order
      await order.update({
        payment_status: 1,
        payment_gateway: 'wallet',
        transaction_id: `WAL${Date.now()}`
      });

      return res.json({ success: true, message: 'Payment successful', data: { order_id: order.id } });
    }

    // TODO: Integrate other payment gateways (Stripe, Razorpay, etc.)

    // Placeholder response for external payment gateways
    const paymentData = {
      order_id: order.id,
      amount: order.total,
      currency: 'INR',
      payment_method,
      // These would be generated by the actual payment gateway
      payment_url: null,
      payment_key: null
    };

    switch (payment_method) {
      case 'stripe':
        // TODO: Create Stripe payment intent
        paymentData.payment_url = `/payments/stripe/${order.id}`;
        break;
      case 'razorpay':
        // TODO: Create Razorpay order
        paymentData.payment_url = `/payments/razorpay/${order.id}`;
        break;
      case 'cashfree':
        // TODO: Create Cashfree session
        paymentData.payment_url = `/payments/cashfree/${order.id}`;
        break;
      default:
        return res.status(400).json({ success: false, error: 'Invalid payment method' });
    }

    res.json({ success: true, data: paymentData });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// Verify payment
router.post('/verify', authenticate, isClient, async (req, res) => {
  try {
    const { order_id, transaction_id, payment_method, payment_response } = req.body;

    const order = await Order.findOne({
      where: { id: order_id, user_id: req.user.id }
    });

    if (!order) {
      return res.status(404).json({ success: false, error: 'Order not found' });
    }

    // TODO: Verify with payment gateway

    await order.update({
      payment_status: 1,
      payment_gateway: payment_method,
      transaction_id
    });

    res.json({ success: true, message: 'Payment verified', data: { order_id: order.id } });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// Payment webhook/IPN handlers
router.post('/webhook/stripe', async (req, res) => {
  try {
    // TODO: Handle Stripe webhook
    res.json({ received: true });
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
});

router.post('/webhook/razorpay', async (req, res) => {
  try {
    // TODO: Handle Razorpay webhook
    res.json({ received: true });
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
});

router.post('/webhook/cashfree', async (req, res) => {
  try {
    // TODO: Handle Cashfree webhook
    res.json({ received: true });
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
});

// Get available payment methods
router.get('/methods', async (req, res) => {
  try {
    // TODO: Fetch from database/settings
    const methods = [
      { id: 'wallet', name: 'Wallet', icon: 'wallet', enabled: true },
      { id: 'stripe', name: 'Credit/Debit Card', icon: 'credit-card', enabled: true },
      { id: 'razorpay', name: 'Razorpay', icon: 'razorpay', enabled: true },
      { id: 'cashfree', name: 'Cashfree', icon: 'cashfree', enabled: true },
      { id: 'cod', name: 'Cash on Delivery', icon: 'cash', enabled: true }
    ];

    res.json({ success: true, data: methods });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

module.exports = router;
